### ISSUE TITLE
Parsing of paper ttl

### ISSUE THREAD

**Issue by adibaba** [dice-group/dice-website#210]
There are errors parsing the ttl files in data/papers.
Mostly it is related to URIs containing `\\_` or `\\%` in **schema:pdfUrl**. In one case, there are 2 URLs in **schema:url**.

**3 types of errors thrown:**

```
success open and validate gatsby-configs - 0.032s
success load plugins - 0.580s
success onPreInit - 0.004s
success initialize cache - 0.007s
success copy gatsby files - 0.021s
success onPreBootstrap - 0.010s
success createSchemaCustomization - 0.005s

 ERROR 

Error parsing papers/24bfac351fe61b29287451d0b2daef180_dice-research.ttl! Error: Unexpected "<http://www.informatica.si/PDF/34-1/04_Ngomo\\%20-\\%20Low-Bias\\%20Extraction\\%20of\\%20Domain-Specific\\%20Concepts.pdf>;" on line 15.
    at N3Lexer._syntaxError (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:470:15)
    at reportSyntaxError (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:391:21)
    at N3Lexer._tokenizeToEnd (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:372:86)
    at Immediate._onImmediate (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:490:14)
    at processImmediate (internal/timers.js:439:21) {
  context: {
    token: undefined,
    line: 15,
    previousToken: { line: 15, type: 'prefixed', value: 'pdfUrl', prefix: 'schema' }
  }
}

⠼ source and transform nodes
/home/linuxbrew/.linuxbrew/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Unexpected "<http://www.informatica.si/PDF/34-1/04_Ngomo\\%20-\\%20Low-Bias\\%20Extraction\\%20of\\%20Domain-Specific\\%20Concepts.pdf>;" on line 15.
    at N3Lexer._syntaxError (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:470:15)
    at reportSyntaxError (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:391:21)
    at N3Lexer._tokenizeToEnd (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:372:86)
    at Immediate._onImmediate (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:490:14)
    at processImmediate (internal/timers.js:439:21) {
  context: {
    token: undefined,
    line: 15,
    previousToken: { line: 15, type: 'prefixed', value: 'pdfUrl', prefix: 'schema' }
  }
}
```

```
gatsby develop                                                         
success open and validate gatsby-configs - 0.032s
success load plugins - 0.564s
success onPreInit - 0.004s
success initialize cache - 0.008s
success copy gatsby files - 0.021s
success onPreBootstrap - 0.011s
success createSchemaCustomization - 0.006s

 ERROR 

Error parsing papers/25a46aca72c5543231ad787408f5e8bd9_dice-research.ttl! Error: Unexpected "<https://doi.org/10.3233/SW-170286;" on line 13.
    at N3Lexer._syntaxError (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:470:15)
    at reportSyntaxError (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:391:21)
    at N3Lexer._tokenizeToEnd (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:372:86)
    at Immediate._onImmediate (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:490:14)
    at processImmediate (internal/timers.js:439:21) {
  context: {
    token: undefined,
    line: 13,
    previousToken: { line: 13, type: 'prefixed', value: 'url', prefix: 'schema' }
  }
}

⠴ source and transform nodes
/home/linuxbrew/.linuxbrew/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Unexpected "<https://doi.org/10.3233/SW-170286;" on line 13.
    at N3Lexer._syntaxError (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:470:15)
    at reportSyntaxError (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:391:21)
    at N3Lexer._tokenizeToEnd (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:372:86)
    at Immediate._onImmediate (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:490:14)
    at processImmediate (internal/timers.js:439:21) {
  context: {
    token: undefined,
    line: 13,
    previousToken: { line: 13, type: 'prefixed', value: 'url', prefix: 'schema' }
  }
}
```

```
gatsby develop                                                         
success open and validate gatsby-configs - 0.032s
success load plugins - 0.564s
success onPreInit - 0.004s
success initialize cache - 0.008s
success copy gatsby files - 0.021s
success onPreBootstrap - 0.011s
success createSchemaCustomization - 0.006s

 ERROR 

Error parsing papers/25a46aca72c5543231ad787408f5e8bd9_dice-research.ttl! Error: Unexpected "<https://doi.org/10.3233/SW-170286;" on line 13.
    at N3Lexer._syntaxError (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:470:15)
    at reportSyntaxError (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:391:21)
    at N3Lexer._tokenizeToEnd (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:372:86)
    at Immediate._onImmediate (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:490:14)
    at processImmediate (internal/timers.js:439:21) {
  context: {
    token: undefined,
    line: 13,
    previousToken: { line: 13, type: 'prefixed', value: 'url', prefix: 'schema' }
  }
}

⠴ source and transform nodes
/home/linuxbrew/.linuxbrew/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Unexpected "<https://doi.org/10.3233/SW-170286;" on line 13.
    at N3Lexer._syntaxError (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:470:15)
    at reportSyntaxError (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:391:21)
    at N3Lexer._tokenizeToEnd (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:372:86)
    at Immediate._onImmediate (/home/adrian/git/dice-website/scripts/node_modules/n3/lib/N3Lexer.js:490:14)
    at processImmediate (internal/timers.js:439:21) {
  context: {
    token: undefined,
    line: 13,
    previousToken: { line: 13, type: 'prefixed', value: 'url', prefix: 'schema' }
  }
}

```

**Can be manually fixed by:**

```
sed -i -- 's/\\\\_/_/g' *
sed -i -- 's/\\\\%/%/g' *
nano ../data/papers/25a46aca72c5543231ad787408f5e8bd9_dice-research.ttl 
```

**Comment by adibaba** [comment]
In Bibsonomy, there are two entries for "GERBIL – Benchmarking Named Entity Recognition and Linking consistently". Each had an URL, which resulted in the following entry in TTL:

`schema:url <https://doi.org/10.3233/SW-170286; http://www.semantic-web-journal.net/system/files/swj1671.pdf>;`

(/data/papers/25a46aca72c5543231ad787408f5e8bd9_dice-research.ttl)

-> I removed one URL in Bobsonomy

**Comment by adibaba** [comment]
I removed `pdfUrl` from papers for now to have at least a working website

Code changes: https://github.com/dice-group/dice-website/commit/05c74d13676ffbbdc9190f1cd63a83bad9c0ec87

**Comment by MichaelRoeder** [comment]
Fixed by introducing two methods. One for checking URLs for their validity and removing invalid URLs and a second method for replacing `\` characters within URLs.

See ae61f4c29046bfe3976e5250ca350cb46f259d98 and c164549dd7534343be7ca9ee51bab526cc6a27e7

**Comment by adibaba** [comment]
well done, thanks!
changes: https://github.com/dice-group/dice-website/compare/495902e80557c8b2a83ac8904b4186ed2fe32704..6f6f84324ede2cf969580de5eaea4e60dafdda70
